### ISSUE TITLE
Environment not found

### ISSUE THREAD

**Issue by danmou** [gforsyth/xonda#10]
I can't activate any environments on my machine (Ubuntu 16.04):
```
$ conda info --envs
# conda environments:
#
py35                     /home/daniel/anaconda3/envs/py35
root                  *  /home/daniel/anaconda3

$ conda activate py35
No environment 'py35' found
```

**Comment by gforsyth** [comment]
Hey @Danmou -- thanks for reporting and sorry about that! Could you do the following, either in `xonsh` or a python repl?

```
from conda import config
print(config.envs_dirs)
```

thanks!

**Comment by danmou** [comment]
No problem! I get the following output:
```('/home/daniel/.conda/envs', '/usr/envs')```

I'm assuming this was supposed to include `/home/daniel/anaconda3/envs`?

**Comment by gforsyth** [comment]
That's what I would've expected. And certainly why it can't find your `py35` environment. Now we just need to figure out how to set the `envs_dirs`...

**Comment by gforsyth** [comment]
Ok, so in your `.condarc` file (or create one if you don't have one) you can add the following:

```
envs_dirs:
  - /home/daniel/anaconda3/envs
```

and then it should work

**Comment by danmou** [comment]
Thanks, that fixed it. Although now py35 is listed twice when I do `conda info --envs` - any idea where it is getting the other one from? I have previously created, removed and recreated the environment so that might be the reason for the problems.

**Comment by gforsyth** [comment]
Maybe `.conda/environments.txt`? Also you should be able to type `conda activate <TAB>` and get a list of available environments from the tab completion.

**Comment by danmou** [comment]
`environments.txt` doesn't seem to affect it. Anyway it's not really a problem so I guess I'll just live with it. Thanks for the help!
