### ISSUE TITLE
conda alias does not allow stdout capturing

### ISSUE THREAD

**Issue by scopatz** [gforsyth/xonda#11]
This was noticed by @asmeurer and I when trying to run `$(conda info -e)`.  The workaround is to run `$($(which -s conda) info -e)`.  Effectively, we skip the alias.

**Comment by gforsyth** [comment]
Thanks for reporting, @scopatz ! Yeah, that's annoying.  I guess using subprocess within the xontrib is swallowing the stdout? I'll play around with it.

**Comment by gforsyth** [comment]
Thanks for checking @asmeurer -- fix is merged and released.
