### ISSUE TITLE
Alias for conda deactivate in .xonshrc not working

### ISSUE THREAD

**Issue by HenningTimm** [gforsyth/xonda#15]
In my .xonshrc I define two aliases, because I am too lazy to type out `conda (de)activate`:

```python
# file: .xonshrc
# conda
aliases["csa"] = "conda activate"
aliases["csd"] = "conda deactivate"
```

The first alias is working fine and I can activate environments like this:

```
$ csa myenv
(myenv) $
```

However, when I want to exit the environment using my alias, the unwrapped conda is used and I get an error. Using the same command (but not as an alias) works:

```
(myenv) $ csd
CommandNotFoundError: 'deactivate is not a conda command.
Did you mean 'source deactivate'?
(myenv) $ aliases["csd"]
['conda', 'deactivate']
(myenv) $ conda deactivate
$ 
```

Any idea what is going wrong here?

**Comment by gforsyth** [comment]
Hey @HenningTimm -- thanks for reporting! Sorry for the delay, I was traveling and am catching up on email. 
I really don't understand what's going on here, hopefully sleeping on it will provide some clarity. I would definitely understand if neither of your aliases worked, but having one work and the other fail is very, very weird.

**Comment by gforsyth** [comment]
For a workaround, you can do the following:

```
from xontrib.xonda import _deactivate
aliases['csd'] = _deactivate
```

**Comment by HenningTimm** [comment]
@gforsyth Thank you for the reply. The workaround is working fine. As far as I am concerned, you can assign a very low priority to this when catching up.
