### ISSUE TITLE
CONDA_PREFIX not set when using conda activate

### ISSUE THREAD

**Issue by bjodah** [gforsyth/xonda#26]
Is this xonda issue or does the ticket belong somewhere else?

xonsh (with xonda):
```
bjorn@yoga720 ~ $ echo $CONDA_PREFIX
$CONDA_PREFIX
bjorn@yoga720 ~ $ conda activate sun3
(sun3) bjorn@yoga720 ~ $ echo $CONDA_PREFIX
$CONDA_PREFIX
```
using bash:
```
bjorn@yoga720:~$ echo $CONDA_PREFIX

bjorn@yoga720:~$ source activate sun3
(sun3) bjorn@yoga720:~$ echo $CONDA_PREFIX
/opt/miniconda3/envs/sun3
```

Supposedly it should be guaranteed to be set:
https://github.com/conda/conda/issues/3694#issuecomment-299548253

This is useful when setting `INCLUDE_PATH` & friends to use versions specific to the current conda environment

**Comment by gforsyth** [comment]
Thanks for reporting! This is a xonda issue. Should be a quick fix when I'm
back in front of a big keyboard. Or I'm happy to look at a PR adding it in.

**Comment by bjodah** [comment]
I tried to address this in gh-27
