### ISSUE TITLE
Most recent version on pypi has builtins bug, that has been fixed on master

### ISSUE THREAD

**Issue by scopatz** [gforsyth/xonda#3]
An update would be nice :)

**Comment by gforsyth** [comment]
I have to get around to automating this stuff...

Updated! https://pypi.python.org/pypi/xonda/0.1.3.dev9

**Comment by scopatz** [comment]
pip doesn't seem to want to download and install this because it is a dev version, even with 

```
$ pip install --upgrade --pre --force-reinstall xonda
```

**Comment by gforsyth** [comment]
Sorry about that, @scopatz !  Just bumped it to `0.1.4` so it should work now.

**Comment by scopatz** [comment]
Thanks!  It installs now
