### ISSUE TITLE
`base` env missing from tab-completion for environments

### ISSUE THREAD

**Issue by michaelaye** [gforsyth/xonda#40]
See screenshot:

![screenshot 2018-10-15 12 50 45](https://user-images.githubusercontent.com/69774/46971407-1662e400-d079-11e8-8073-e45e0ffb3f08.png)

**Comment by gforsyth** [comment]
ahh, yeah, so there's another implicit assumption that the "base" env is the default, so you get it by running `conda deactivate`, but we can add it to the list

**Comment by michaelaye** [comment]
That's not necessarily true, because in my case, I launch xonsh from a fish, where my conda default env is py37:

```bash
(py37) klay6683@MacL2938 ~/Dropbox/src $ conda deactivate
klay6683@MacL2938 ~/Dropbox/src $ which ipython
/Users/klay6683/miniconda3/envs/py37/bin/ipython
klay6683@MacL2938 ~/Dropbox/src $
```

**Comment by gforsyth** [comment]
Yeah, this is missing functionality.  I'll try to add it in later this week.
