### ISSUE TITLE
Too many significant digits when download conda packages

### ISSUE THREAD

**Issue by hmaarrfk** [gforsyth/xonda#42]
Did anybody notice that there are too many digits being displayed when conda is downloading packages?

Seems like something that didn't used to happen when I was using bash. It makes it really difficult to use even modest sized terminal windows.

**Comment by gforsyth** [comment]
Hi @hmaarrfk -- can you confirm that the number of digits is different in bash using your current version of `conda`?
Thanks!

**Comment by hmaarrfk** [comment]
With xonda + xonsh

![image](https://user-images.githubusercontent.com/90008/48557396-f9e0f280-e929-11e8-87bb-9d0965165916.png)

My internet is slow, but it does the hashtag/pound sign progress bar on bash`#########123456789`
with bash
![image](https://user-images.githubusercontent.com/90008/48557589-84c1ed00-e92a-11e8-9ac1-f7470ea1b49c.png)

**Comment by gforsyth** [comment]
Ok, thanks, would you mind opening this up at `xonsh/xonsh`?  Because I think this is a more of a `xonsh` issue than a `xonda` one.

**Comment by hmaarrfk** [comment]
seems to be fixed.
