### ISSUE TITLE
Problem activating env from .autoxsh

### ISSUE THREAD

**Issue by meatballs** [gforsyth/xonda#46]
If I activate an environment using

```
conda activate my_env
```

everything works as expected. However if I create a `.autoxsh' file using

```
echo "conda activate my_env" > .autoxsh
```

and then change into that directory, I get the conda usage message and the env is not activated:

```
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '<path>/.autoxsh' (choose from 'clean', 'config', 'create', 'help', 'info', 'init', 'install', 'list', 'package', 'remove', 'uninstall', 'run', 'search', 'update', 'upgrade')
```

(If this isn't a xonda issue and belongs somewhere else, just shout and I'll raised wherever it needs to be)!

**Comment by gforsyth** [comment]
I'm not super familiar with the `autoxsh` internals, but that looks like an issue on that end since it's passing `<path>/.autoxsh` to `conda`

**Comment by meatballs** [comment]
I shall have a poke around in there!
