### ISSUE TITLE
put on conda-forge?

### ISSUE THREAD

**Issue by CJ-Wright** [gforsyth/xonda#8]
Is there any interest in putting on conda forge?

**Comment by gforsyth** [comment]
Sure!

**Comment by CJ-Wright** [comment]
I noticed that most of the xonsh xontribs were pip affairs, so I will try to conda-forge them at some point. (Btw, I am very sorry that I didn't put some sort of `I put xonda inside your conda so you can conda while you xonda` meme/pun here)
